# Generated by Django 4.2.6 on 2023-10-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('roast', models.TextField()),
                ('species', models.TextField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coffee')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flavor')),
            ],
        ),
        migrations.AddField(
            model_name='coffee',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.origin'),
        ),
    ]
