# Generated by Django 4.2.7 on 2024-01-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usergroup_added_at_usergroup_group_usergroup_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
