# Generated by Django 4.2.7 on 2024-01-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usergroup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
