# Generated by Django 4.2.7 on 2024-01-20 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usergroup2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='api.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergroup',
            name='user',
            field=models.ForeignKey(default='be9537c0-6bda-4966-9aeb-6fdead80f267', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='UserGroup2',
        ),
    ]
