# Generated by Django 4.2.7 on 2024-01-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usergroup_added_at_usergroup_group_usergroup_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='usergroup',
            old_name='user',
            new_name='user_id',
        ),
    ]
