# Generated by Django 4.2.7 on 2024-01-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_group_usergroup_group_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='usergroup',
            old_name='user_id',
            new_name='user',
        ),
    ]
