# Generated by Django 4.2.7 on 2024-01-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_usergroup_group_remove_usergroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to='api.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergroup',
            name='user',
            field=models.ForeignKey(default='f2abcfa9-6320-4da2-961d-b78f915b7ca6', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
    ]
