# Generated by Django 4.2.7 on 2024-01-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_usergroup_group_usergroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='ratings',
            field=models.ManyToManyField(blank=True, through='api.CoffeeRating', to='api.user'),
        ),
        migrations.AlterField(
            model_name='coffeerating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
