# Generated by Django 4.2.7 on 2024-01-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_coffee_ratings_alter_coffeerating_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coffeerating',
            unique_together=set(),
        ),
    ]
