# Generated by Django 4.2.7 on 2024-01-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_coffeerating_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coffeerating',
            unique_together={('coffee', 'user')},
        ),
    ]
