# Generated by Django 4.2.7 on 2024-01-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_coffeerating_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeerating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
