# Generated by Django 4.2.7 on 2024-01-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_coffee_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeerating',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
