# Generated by Django 4.2.7 on 2024-01-25 18:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_coffee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='CoffeeImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('image',)},
            },
        ),
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coffeeimage'),
        ),
    ]
